#!/bin/bash
###############################################
# install                                     #
#                                             #
#    This script, called by an EC2 instance   #
# at first launch, sets up the development    #
# environment.                                #
###############################################

set -x

# Install pyenv
if [ ! -d ~/.pyenv ]
then
	# Install pyenv
	export PYENV_ROOT="$HOME/.pyenv"
	export PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"
	git clone https://github.com/pyenv/pyenv.git $PYENV_ROOT
	git clone https://github.com/pyenv/pyenv-update.git $PYENV_ROOT/plugins/pyenv-update
	git clone https://github.com/pyenv/pyenv-virtualenv.git $PYENV_ROOT/plugins/pyenv-virtualenv

	tee -a ~/.profile <<-'EOF'
		export PATH="$HOME/.pyenv/bin:$PATH"
		eval "$(pyenv init -)"
		eval "$(pyenv virtualenv-init -)"
EOF
	export PATH="$HOME/.pyenv/bin:$PATH"
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"

	pyenv install 3.8.2 && pyenv global 3.8.2
else
	export PATH="$HOME/.pyenv/bin:$PATH"
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
	pyenv rehash
fi


# Change shell to zsh
printf "\nChanging shell to zsh and installing oh-my-zsh...\n"
chsh -s $(which zsh)
# Install oh-my-zsh
curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/zsh_install.sh
chmod u+x ~/zsh_install.sh
sh -c ~/zsh_install.sh && rm ~/zsh_install.sh


# Copy over dotfiles from this repo
printf "\nCopying dotfiles to $HOME...\n"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cat ${DIR}/.gitconfig >> ~/.gitconfig
cat ${DIR}/.bash_aliases >> ~/.bash_aliases
cat ${DIR}/.tmux.conf >> ~/.tmux.conf
rsync -az ${DIR}/.ssh ~/


# Symlink all *.symlink files
# TODO: Move other dotfiles to symlink setup
printf "\nSymlinking dotfiles...\n"
for SOURCE_FILE in $(find $(pwd) -name '*.symlink'); do
  LINK_FILE="$HOME/.$(basename ${SOURCE_FILE%.symlink})"
  ln -sv "$SOURCE_FILE" $LINK_FILE;
done

exit 0

